import './globals.css'
import {  Zilla_Slab } from 'next/font/google'
import Header from '@/components/header'

const zillaSlab = Zilla_Slab({ subsets: ['latin'] ,weight:['400','500','600','700'],style:['normal']})

export const metadata = {
  title: 'Asian Kitchen',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body className={zillaSlab.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  )
}
